---
- hosts: localhost
  connection: local
  vars_files:
    - ~/ansible/vars.yml
  tasks:
    - name: Creating resource group - "{{ rgname }}"
      azure_rm_resourcegroup:
        name: "{{ rgname }}"
        location: "{{ loc }}"
      register: rg
    - debug:
        var: rg