- name: Create an Azure Linux VM
  hosts: localhost
  connection: local
  vars_files:
    - ~/ansible/vars/ext_vars.yml
  tasks:
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ rgname }}"
      name: "{{ name }}-{{ vm }}-nsg1"
      rules:
        - name: AllowWebTraffic
          protocol: Tcp
          destination_port_range: 
            - 80
            - 443
          access: Allow
          priority: 1000
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ rgname }}"
      name: "{{ name }}-{{ vm }}-nic1"
      virtual_network: "{{ name }}-vnet1"
      subnet: "{{ name }}-subnet2"
      public_ip_name: "{{ name }}-{{ vm }}-pip1"
      security_group: "{{ name }}-{{ vm }}-nsg1"
