---
- name: Adding Updates
  hosts: servers
  become: yes
  tasks:
    - name: Updating
      yum:
        name: "*"
        state: latest
    - name: Updating
      yum:
        name: httpd
        state: latest
    - name: Starting Service
      service:
        name: httpd
        enabled: yes
        state: started
