---
- name: Adding Updates
  hosts: hosts
  become: yes
  tasks:
    - name: Updating
      dnf:
        name: "*"
        state: latest
    - name: Updating
      dnf:
        name: httpd
        state: latest
    - name: Starting Service
      service:
        name: httpd
        # enabled: yes
        state: restarted
